# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-16 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '动画',
                'db_table': 'tb_animate',
                'verbose_name_plural': '动画',
            },
        ),
        migrations.CreateModel(
            name='CateGory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='ImageBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relative_path', models.CharField(blank=True, max_length=200, null=True)),
                ('chapter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('animate', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='animate.Animate')),
            ],
            options={
                'db_table': 'tb_imagebase',
            },
        ),
        migrations.AddField(
            model_name='animate',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animate.CateGory'),
        ),
    ]
