# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-01-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animate',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='imagebase',
            index_together=set([('chapter', 'page_number')]),
        ),
    ]
