# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgtype.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msgtype.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmsgtype.proto\"[\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nchannel_id\x18\x02 \x01(\t\x12\x13\n\x0b\x61rticle_num\x18\x03 \x01(\t\x12\x12\n\ntime_stamp\x18\x04 \x01(\t\"E\n\x06Tracks\x12\r\n\x05\x63lick\x18\x01 \x01(\t\x12\x0f\n\x07\x63ollect\x18\x02 \x01(\t\x12\r\n\x05share\x18\x03 \x01(\t\x12\x0c\n\x04read\x18\x04 \x01(\t\"7\n\tRecommand\x12\x12\n\narticle_id\x18\x01 \x01(\t\x12\x16\n\x05track\x18\x02 \x01(\x0b\x32\x07.Tracks\"W\n\x0f\x41rticleResponse\x12\x10\n\x08\x65xpousre\x18\x01 \x01(\t\x12\x12\n\ntime_stamp\x18\x02 \x01(\t\x12\x1e\n\nrecommends\x18\x03 \x03(\x0b\x32\n.Recommand2k\n\x0eTheServerClass\x12+\n\x07\x46irstFn\x12\x0c.UserRequest\x1a\x10.ArticleResponse\"\x00\x12,\n\x08SecondFn\x12\x0c.UserRequest\x1a\x10.ArticleResponse\"\x00\x62\x06proto3')
)




_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='UserRequest.channel_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='article_num', full_name='UserRequest.article_num', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='UserRequest.time_stamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=108,
)


_TRACKS = _descriptor.Descriptor(
  name='Tracks',
  full_name='Tracks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='click', full_name='Tracks.click', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collect', full_name='Tracks.collect', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='share', full_name='Tracks.share', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read', full_name='Tracks.read', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=179,
)


_RECOMMAND = _descriptor.Descriptor(
  name='Recommand',
  full_name='Recommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='article_id', full_name='Recommand.article_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track', full_name='Recommand.track', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=236,
)


_ARTICLERESPONSE = _descriptor.Descriptor(
  name='ArticleResponse',
  full_name='ArticleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expousre', full_name='ArticleResponse.expousre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='ArticleResponse.time_stamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recommends', full_name='ArticleResponse.recommends', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=325,
)

_RECOMMAND.fields_by_name['track'].message_type = _TRACKS
_ARTICLERESPONSE.fields_by_name['recommends'].message_type = _RECOMMAND
DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['Tracks'] = _TRACKS
DESCRIPTOR.message_types_by_name['Recommand'] = _RECOMMAND
DESCRIPTOR.message_types_by_name['ArticleResponse'] = _ARTICLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERREQUEST,
  __module__ = 'msgtype_pb2'
  # @@protoc_insertion_point(class_scope:UserRequest)
  ))
_sym_db.RegisterMessage(UserRequest)

Tracks = _reflection.GeneratedProtocolMessageType('Tracks', (_message.Message,), dict(
  DESCRIPTOR = _TRACKS,
  __module__ = 'msgtype_pb2'
  # @@protoc_insertion_point(class_scope:Tracks)
  ))
_sym_db.RegisterMessage(Tracks)

Recommand = _reflection.GeneratedProtocolMessageType('Recommand', (_message.Message,), dict(
  DESCRIPTOR = _RECOMMAND,
  __module__ = 'msgtype_pb2'
  # @@protoc_insertion_point(class_scope:Recommand)
  ))
_sym_db.RegisterMessage(Recommand)

ArticleResponse = _reflection.GeneratedProtocolMessageType('ArticleResponse', (_message.Message,), dict(
  DESCRIPTOR = _ARTICLERESPONSE,
  __module__ = 'msgtype_pb2'
  # @@protoc_insertion_point(class_scope:ArticleResponse)
  ))
_sym_db.RegisterMessage(ArticleResponse)



_THESERVERCLASS = _descriptor.ServiceDescriptor(
  name='TheServerClass',
  full_name='TheServerClass',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=327,
  serialized_end=434,
  methods=[
  _descriptor.MethodDescriptor(
    name='FirstFn',
    full_name='TheServerClass.FirstFn',
    index=0,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_ARTICLERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SecondFn',
    full_name='TheServerClass.SecondFn',
    index=1,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_ARTICLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_THESERVERCLASS)

DESCRIPTOR.services_by_name['TheServerClass'] = _THESERVERCLASS

# @@protoc_insertion_point(module_scope)
